/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedClientReclamationsRouteImport } from './routes/_authenticated.client.reclamations'
import { Route as AuthenticatedClientRdvNouveauRouteImport } from './routes/_authenticated.client.rdv-nouveau'
import { Route as AuthenticatedClientProfilRouteImport } from './routes/_authenticated.client.profil'
import { Route as AuthenticatedClientHistoriqueRouteImport } from './routes/_authenticated.client.historique'
import { Route as AuthenticatedClientFaqRouteImport } from './routes/_authenticated.client.faq'
import { Route as AuthenticatedClientDashboardRouteImport } from './routes/_authenticated.client.dashboard'
import { Route as AuthenticatedBackOfficeStatistiquesRouteImport } from './routes/_authenticated.back-office.statistiques'
import { Route as AuthenticatedBackOfficeReclamationsRouteImport } from './routes/_authenticated.back-office.reclamations'
import { Route as AuthenticatedBackOfficeRdvRouteImport } from './routes/_authenticated.back-office.rdv'
import { Route as AuthenticatedBackOfficePlanningsRouteImport } from './routes/_authenticated.back-office.plannings'
import { Route as AuthenticatedBackOfficeDashboardRouteImport } from './routes/_authenticated.back-office.dashboard'
import { Route as AuthenticatedBackOfficeAgencesRouteImport } from './routes/_authenticated.back-office.agences'
import { Route as AuthenticatedAgentFoReclamationsRouteImport } from './routes/_authenticated.agent-fo.reclamations'
import { Route as AuthenticatedAgentFoRdvNouveauRouteImport } from './routes/_authenticated.agent-fo.rdv-nouveau'
import { Route as AuthenticatedAgentFoDashboardRouteImport } from './routes/_authenticated.agent-fo.dashboard'
import { Route as AuthenticatedAgentFoClientsRouteImport } from './routes/_authenticated.agent-fo.clients'
import { Route as AuthenticatedClientRdvIdRouteImport } from './routes/_authenticated.client.rdv.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientReclamationsRoute =
  AuthenticatedClientReclamationsRouteImport.update({
    id: '/client/reclamations',
    path: '/client/reclamations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientRdvNouveauRoute =
  AuthenticatedClientRdvNouveauRouteImport.update({
    id: '/client/rdv-nouveau',
    path: '/client/rdv-nouveau',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientProfilRoute =
  AuthenticatedClientProfilRouteImport.update({
    id: '/client/profil',
    path: '/client/profil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientHistoriqueRoute =
  AuthenticatedClientHistoriqueRouteImport.update({
    id: '/client/historique',
    path: '/client/historique',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientFaqRoute = AuthenticatedClientFaqRouteImport.update({
  id: '/client/faq',
  path: '/client/faq',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientDashboardRoute =
  AuthenticatedClientDashboardRouteImport.update({
    id: '/client/dashboard',
    path: '/client/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeStatistiquesRoute =
  AuthenticatedBackOfficeStatistiquesRouteImport.update({
    id: '/back-office/statistiques',
    path: '/back-office/statistiques',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeReclamationsRoute =
  AuthenticatedBackOfficeReclamationsRouteImport.update({
    id: '/back-office/reclamations',
    path: '/back-office/reclamations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeRdvRoute =
  AuthenticatedBackOfficeRdvRouteImport.update({
    id: '/back-office/rdv',
    path: '/back-office/rdv',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficePlanningsRoute =
  AuthenticatedBackOfficePlanningsRouteImport.update({
    id: '/back-office/plannings',
    path: '/back-office/plannings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeDashboardRoute =
  AuthenticatedBackOfficeDashboardRouteImport.update({
    id: '/back-office/dashboard',
    path: '/back-office/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBackOfficeAgencesRoute =
  AuthenticatedBackOfficeAgencesRouteImport.update({
    id: '/back-office/agences',
    path: '/back-office/agences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentFoReclamationsRoute =
  AuthenticatedAgentFoReclamationsRouteImport.update({
    id: '/agent-fo/reclamations',
    path: '/agent-fo/reclamations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentFoRdvNouveauRoute =
  AuthenticatedAgentFoRdvNouveauRouteImport.update({
    id: '/agent-fo/rdv-nouveau',
    path: '/agent-fo/rdv-nouveau',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentFoDashboardRoute =
  AuthenticatedAgentFoDashboardRouteImport.update({
    id: '/agent-fo/dashboard',
    path: '/agent-fo/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentFoClientsRoute =
  AuthenticatedAgentFoClientsRouteImport.update({
    id: '/agent-fo/clients',
    path: '/agent-fo/clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientRdvIdRoute =
  AuthenticatedClientRdvIdRouteImport.update({
    id: '/client/rdv/$id',
    path: '/client/rdv/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-fo/clients': typeof AuthenticatedAgentFoClientsRoute
  '/agent-fo/dashboard': typeof AuthenticatedAgentFoDashboardRoute
  '/agent-fo/rdv-nouveau': typeof AuthenticatedAgentFoRdvNouveauRoute
  '/agent-fo/reclamations': typeof AuthenticatedAgentFoReclamationsRoute
  '/back-office/agences': typeof AuthenticatedBackOfficeAgencesRoute
  '/back-office/dashboard': typeof AuthenticatedBackOfficeDashboardRoute
  '/back-office/plannings': typeof AuthenticatedBackOfficePlanningsRoute
  '/back-office/rdv': typeof AuthenticatedBackOfficeRdvRoute
  '/back-office/reclamations': typeof AuthenticatedBackOfficeReclamationsRoute
  '/back-office/statistiques': typeof AuthenticatedBackOfficeStatistiquesRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/faq': typeof AuthenticatedClientFaqRoute
  '/client/historique': typeof AuthenticatedClientHistoriqueRoute
  '/client/profil': typeof AuthenticatedClientProfilRoute
  '/client/rdv-nouveau': typeof AuthenticatedClientRdvNouveauRoute
  '/client/reclamations': typeof AuthenticatedClientReclamationsRoute
  '/client/rdv/$id': typeof AuthenticatedClientRdvIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agent-fo/clients': typeof AuthenticatedAgentFoClientsRoute
  '/agent-fo/dashboard': typeof AuthenticatedAgentFoDashboardRoute
  '/agent-fo/rdv-nouveau': typeof AuthenticatedAgentFoRdvNouveauRoute
  '/agent-fo/reclamations': typeof AuthenticatedAgentFoReclamationsRoute
  '/back-office/agences': typeof AuthenticatedBackOfficeAgencesRoute
  '/back-office/dashboard': typeof AuthenticatedBackOfficeDashboardRoute
  '/back-office/plannings': typeof AuthenticatedBackOfficePlanningsRoute
  '/back-office/rdv': typeof AuthenticatedBackOfficeRdvRoute
  '/back-office/reclamations': typeof AuthenticatedBackOfficeReclamationsRoute
  '/back-office/statistiques': typeof AuthenticatedBackOfficeStatistiquesRoute
  '/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/client/faq': typeof AuthenticatedClientFaqRoute
  '/client/historique': typeof AuthenticatedClientHistoriqueRoute
  '/client/profil': typeof AuthenticatedClientProfilRoute
  '/client/rdv-nouveau': typeof AuthenticatedClientRdvNouveauRoute
  '/client/reclamations': typeof AuthenticatedClientReclamationsRoute
  '/client/rdv/$id': typeof AuthenticatedClientRdvIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agent-fo/clients': typeof AuthenticatedAgentFoClientsRoute
  '/_authenticated/agent-fo/dashboard': typeof AuthenticatedAgentFoDashboardRoute
  '/_authenticated/agent-fo/rdv-nouveau': typeof AuthenticatedAgentFoRdvNouveauRoute
  '/_authenticated/agent-fo/reclamations': typeof AuthenticatedAgentFoReclamationsRoute
  '/_authenticated/back-office/agences': typeof AuthenticatedBackOfficeAgencesRoute
  '/_authenticated/back-office/dashboard': typeof AuthenticatedBackOfficeDashboardRoute
  '/_authenticated/back-office/plannings': typeof AuthenticatedBackOfficePlanningsRoute
  '/_authenticated/back-office/rdv': typeof AuthenticatedBackOfficeRdvRoute
  '/_authenticated/back-office/reclamations': typeof AuthenticatedBackOfficeReclamationsRoute
  '/_authenticated/back-office/statistiques': typeof AuthenticatedBackOfficeStatistiquesRoute
  '/_authenticated/client/dashboard': typeof AuthenticatedClientDashboardRoute
  '/_authenticated/client/faq': typeof AuthenticatedClientFaqRoute
  '/_authenticated/client/historique': typeof AuthenticatedClientHistoriqueRoute
  '/_authenticated/client/profil': typeof AuthenticatedClientProfilRoute
  '/_authenticated/client/rdv-nouveau': typeof AuthenticatedClientRdvNouveauRoute
  '/_authenticated/client/reclamations': typeof AuthenticatedClientReclamationsRoute
  '/_authenticated/client/rdv/$id': typeof AuthenticatedClientRdvIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent-fo/clients'
    | '/agent-fo/dashboard'
    | '/agent-fo/rdv-nouveau'
    | '/agent-fo/reclamations'
    | '/back-office/agences'
    | '/back-office/dashboard'
    | '/back-office/plannings'
    | '/back-office/rdv'
    | '/back-office/reclamations'
    | '/back-office/statistiques'
    | '/client/dashboard'
    | '/client/faq'
    | '/client/historique'
    | '/client/profil'
    | '/client/rdv-nouveau'
    | '/client/reclamations'
    | '/client/rdv/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agent-fo/clients'
    | '/agent-fo/dashboard'
    | '/agent-fo/rdv-nouveau'
    | '/agent-fo/reclamations'
    | '/back-office/agences'
    | '/back-office/dashboard'
    | '/back-office/plannings'
    | '/back-office/rdv'
    | '/back-office/reclamations'
    | '/back-office/statistiques'
    | '/client/dashboard'
    | '/client/faq'
    | '/client/historique'
    | '/client/profil'
    | '/client/rdv-nouveau'
    | '/client/reclamations'
    | '/client/rdv/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agent-fo/clients'
    | '/_authenticated/agent-fo/dashboard'
    | '/_authenticated/agent-fo/rdv-nouveau'
    | '/_authenticated/agent-fo/reclamations'
    | '/_authenticated/back-office/agences'
    | '/_authenticated/back-office/dashboard'
    | '/_authenticated/back-office/plannings'
    | '/_authenticated/back-office/rdv'
    | '/_authenticated/back-office/reclamations'
    | '/_authenticated/back-office/statistiques'
    | '/_authenticated/client/dashboard'
    | '/_authenticated/client/faq'
    | '/_authenticated/client/historique'
    | '/_authenticated/client/profil'
    | '/_authenticated/client/rdv-nouveau'
    | '/_authenticated/client/reclamations'
    | '/_authenticated/client/rdv/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/client/reclamations': {
      id: '/_authenticated/client/reclamations'
      path: '/client/reclamations'
      fullPath: '/client/reclamations'
      preLoaderRoute: typeof AuthenticatedClientReclamationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/rdv-nouveau': {
      id: '/_authenticated/client/rdv-nouveau'
      path: '/client/rdv-nouveau'
      fullPath: '/client/rdv-nouveau'
      preLoaderRoute: typeof AuthenticatedClientRdvNouveauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/profil': {
      id: '/_authenticated/client/profil'
      path: '/client/profil'
      fullPath: '/client/profil'
      preLoaderRoute: typeof AuthenticatedClientProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/historique': {
      id: '/_authenticated/client/historique'
      path: '/client/historique'
      fullPath: '/client/historique'
      preLoaderRoute: typeof AuthenticatedClientHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/faq': {
      id: '/_authenticated/client/faq'
      path: '/client/faq'
      fullPath: '/client/faq'
      preLoaderRoute: typeof AuthenticatedClientFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/dashboard': {
      id: '/_authenticated/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof AuthenticatedClientDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office/statistiques': {
      id: '/_authenticated/back-office/statistiques'
      path: '/back-office/statistiques'
      fullPath: '/back-office/statistiques'
      preLoaderRoute: typeof AuthenticatedBackOfficeStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office/reclamations': {
      id: '/_authenticated/back-office/reclamations'
      path: '/back-office/reclamations'
      fullPath: '/back-office/reclamations'
      preLoaderRoute: typeof AuthenticatedBackOfficeReclamationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office/rdv': {
      id: '/_authenticated/back-office/rdv'
      path: '/back-office/rdv'
      fullPath: '/back-office/rdv'
      preLoaderRoute: typeof AuthenticatedBackOfficeRdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office/plannings': {
      id: '/_authenticated/back-office/plannings'
      path: '/back-office/plannings'
      fullPath: '/back-office/plannings'
      preLoaderRoute: typeof AuthenticatedBackOfficePlanningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office/dashboard': {
      id: '/_authenticated/back-office/dashboard'
      path: '/back-office/dashboard'
      fullPath: '/back-office/dashboard'
      preLoaderRoute: typeof AuthenticatedBackOfficeDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/back-office/agences': {
      id: '/_authenticated/back-office/agences'
      path: '/back-office/agences'
      fullPath: '/back-office/agences'
      preLoaderRoute: typeof AuthenticatedBackOfficeAgencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-fo/reclamations': {
      id: '/_authenticated/agent-fo/reclamations'
      path: '/agent-fo/reclamations'
      fullPath: '/agent-fo/reclamations'
      preLoaderRoute: typeof AuthenticatedAgentFoReclamationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-fo/rdv-nouveau': {
      id: '/_authenticated/agent-fo/rdv-nouveau'
      path: '/agent-fo/rdv-nouveau'
      fullPath: '/agent-fo/rdv-nouveau'
      preLoaderRoute: typeof AuthenticatedAgentFoRdvNouveauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-fo/dashboard': {
      id: '/_authenticated/agent-fo/dashboard'
      path: '/agent-fo/dashboard'
      fullPath: '/agent-fo/dashboard'
      preLoaderRoute: typeof AuthenticatedAgentFoDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent-fo/clients': {
      id: '/_authenticated/agent-fo/clients'
      path: '/agent-fo/clients'
      fullPath: '/agent-fo/clients'
      preLoaderRoute: typeof AuthenticatedAgentFoClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client/rdv/$id': {
      id: '/_authenticated/client/rdv/$id'
      path: '/client/rdv/$id'
      fullPath: '/client/rdv/$id'
      preLoaderRoute: typeof AuthenticatedClientRdvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgentFoClientsRoute: typeof AuthenticatedAgentFoClientsRoute
  AuthenticatedAgentFoDashboardRoute: typeof AuthenticatedAgentFoDashboardRoute
  AuthenticatedAgentFoRdvNouveauRoute: typeof AuthenticatedAgentFoRdvNouveauRoute
  AuthenticatedAgentFoReclamationsRoute: typeof AuthenticatedAgentFoReclamationsRoute
  AuthenticatedBackOfficeAgencesRoute: typeof AuthenticatedBackOfficeAgencesRoute
  AuthenticatedBackOfficeDashboardRoute: typeof AuthenticatedBackOfficeDashboardRoute
  AuthenticatedBackOfficePlanningsRoute: typeof AuthenticatedBackOfficePlanningsRoute
  AuthenticatedBackOfficeRdvRoute: typeof AuthenticatedBackOfficeRdvRoute
  AuthenticatedBackOfficeReclamationsRoute: typeof AuthenticatedBackOfficeReclamationsRoute
  AuthenticatedBackOfficeStatistiquesRoute: typeof AuthenticatedBackOfficeStatistiquesRoute
  AuthenticatedClientDashboardRoute: typeof AuthenticatedClientDashboardRoute
  AuthenticatedClientFaqRoute: typeof AuthenticatedClientFaqRoute
  AuthenticatedClientHistoriqueRoute: typeof AuthenticatedClientHistoriqueRoute
  AuthenticatedClientProfilRoute: typeof AuthenticatedClientProfilRoute
  AuthenticatedClientRdvNouveauRoute: typeof AuthenticatedClientRdvNouveauRoute
  AuthenticatedClientReclamationsRoute: typeof AuthenticatedClientReclamationsRoute
  AuthenticatedClientRdvIdRoute: typeof AuthenticatedClientRdvIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentFoClientsRoute: AuthenticatedAgentFoClientsRoute,
  AuthenticatedAgentFoDashboardRoute: AuthenticatedAgentFoDashboardRoute,
  AuthenticatedAgentFoRdvNouveauRoute: AuthenticatedAgentFoRdvNouveauRoute,
  AuthenticatedAgentFoReclamationsRoute: AuthenticatedAgentFoReclamationsRoute,
  AuthenticatedBackOfficeAgencesRoute: AuthenticatedBackOfficeAgencesRoute,
  AuthenticatedBackOfficeDashboardRoute: AuthenticatedBackOfficeDashboardRoute,
  AuthenticatedBackOfficePlanningsRoute: AuthenticatedBackOfficePlanningsRoute,
  AuthenticatedBackOfficeRdvRoute: AuthenticatedBackOfficeRdvRoute,
  AuthenticatedBackOfficeReclamationsRoute:
    AuthenticatedBackOfficeReclamationsRoute,
  AuthenticatedBackOfficeStatistiquesRoute:
    AuthenticatedBackOfficeStatistiquesRoute,
  AuthenticatedClientDashboardRoute: AuthenticatedClientDashboardRoute,
  AuthenticatedClientFaqRoute: AuthenticatedClientFaqRoute,
  AuthenticatedClientHistoriqueRoute: AuthenticatedClientHistoriqueRoute,
  AuthenticatedClientProfilRoute: AuthenticatedClientProfilRoute,
  AuthenticatedClientRdvNouveauRoute: AuthenticatedClientRdvNouveauRoute,
  AuthenticatedClientReclamationsRoute: AuthenticatedClientReclamationsRoute,
  AuthenticatedClientRdvIdRoute: AuthenticatedClientRdvIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
